language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
addons:
  postgresql: "9.4"  
before_script:
  - psql -c "CREATE USER pybossa WITH PASSWORD 'tester';" -U postgres
  - psql -c "CREATE DATABASE cs WITH OWNER pybossa;" -U postgres 
services:
  - postgresql
script:
  - pytest test_*
