language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
addons:
  postgresql: "9.4"
before_script:
  - psql -c "CREATE USER testing WITH PASSWORD 'testing';" -U postgres
  - psql -c "CREATE DATABASE cs WITH OWNER testing;" -U postgres
services:
  - postgresql
script:
  - ln -sf envs/travis.env .env
  - pytest test/
notifications:
  webhooks: https://chat.citizenscience.ch/hooks/HyKJmkFFsxjNTx2ce/RkjhJoNPEXLgnCbpKnkDL4iodkZhiCdRxGKaM8mu79mAcmRx

