language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
before_script:
  - psql -c 'CREATE USER pybossa WITH PASSWORD \'tester\';' -U postgres 
  - psql -c 'CREATE DATABASE cs WITH OWNER \'pybossa\';' -U postgres 
services:
  - postgresql
script:
  - CC_ENV=config/test.py pytest
