language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
addons:
  postgresql: "9.4"  
before_script:
  - psql -c "CREATE USER testing WITH PASSWORD 'tester';" -U postgres
  - psql -c "CREATE DATABASE testcs WITH OWNER testing;" -U postgres
services:
  - postgresql
script:
  - ln -sf envs/test.env .env
  - pytest test/
notifications:
  webhooks: https://chat.citizenscience.ch/hooks/xnYY4LLB2LWXqmxHd/ABijvSTDjRoNvPLin6JyLTRyBDGNQTDmihLutzRcT5bDHmWg

