FROM python:3.6.6-stretch
ENV PYTHONUNBUFFERED 1
ARG CC_ENV
RUN mkdir /code
WORKDIR /code
ADD requirements.txt .
RUN pip3 install -r requirements.txt
ADD . /code/
COPY --from=0 /expand/swagger_complete.yaml /code/swagger/swagger_complete.yaml
RUN pytest test
