version: '3.2'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_DB: ${PG_DATABASE}
  cccs-connexion:
    build:
      context: .
      args:
        SW_ENV: envs/test.env
    command: pytest test/
    depends_on:
      - db
