version: '3'

services:
  db:
    build:
      context: .
      dockerfile: scripts/pg/Dockerfile
    restart: always
    ports:
    - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_DB=${PG_DB}
  api:
    network_mode: host
    build:
      context: .
    command:  uwsgi --http :${CC_PORT} --wsgi-file uwsgi.py --master --processes 4 --threads 2 --stats :9191
    depends_on:
      - db
    ports:
      - "${CC_PORT}:${CC_PORT}"
