
FROM node:8-alpine
ENV SWAGGER_DIR openapi/
ENV SWAGGER_SRC oapi.yaml
ENV SWAGGER_FILE cc.yaml
COPY $SWAGGER_DIR .
RUN npm i -g speccy
RUN speccy resolve $SWAGGERDIR$SWAGGER_SRC > $SWAGGER_FILE

FROM python:3.7-alpine
RUN apk add build-base
RUN apk add postgresql-dev
RUN apk add libffi-dev
ENV PYTHONUNBUFFERED 1
ENV CC_PORT 9000
ARG SWAGGER_DIR
ARG SWAGGER_FILE
RUN mkdir /code
WORKDIR /code
RUN pip install --upgrade pip
ADD requirements.txt .
RUN pip3 install -r requirements.txt
COPY . /code/
COPY --from=0 $SWAGGER_FILE /code/$SWAGGER_DIR$SWAGGER_FILE
EXPOSE 9000:$CC_PORT