swagger: '2.0'
info:
  title: CCCS
  version: "0.1"
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  apiKeyHeader:
    type: apiKey
    in: header
    name: X-API-KEY
  oauth2:
    type: oauth2
    flow: implicit
    authorizationUrl: http://172.23.52.127:8081/oauth/authorize
    # the token info URL is hardcoded for our mock_tokeninfo.py script
    # you can also pass it as an environment variable TOKENINFO_URL
    x-tokenInfoUrl: http://172.23.52.127:8081/api/v1/users/validate
    scopes:
      apiKey: Unique identifier of the user accessing the service.
host: 172.23.52.127:8080
basePath: /api/v1
schemes:
  - http
paths:
  /users:
    get:
      tags: [Users]
      x-swagger-router-controller: api.user
      operationId: get_users
      parameters:
        - name: search_term
          in: query
          type: string
        - name: limit
          in: query
          type: integer
          minimum: 0
          default: 20
      responses:
        200:
          description: Return all users
          schema:
            type: array
            items:  
              $ref: '#/definitions/User'
  /users/authorize:
    post:
      tags: [Users]
      x-swagger-router-controller: api.otoken
      operationId: generate
      summary: Post auth for token response
      parameters:
        - name: token
          in: body
          schema:
            $ref: '#/definitions/Otoken'
      responses:
        200:
          description: Token created
  /users/validate:
    get:
      tags: [Users]
      summary: OAuth2 token info
      x-swagger-router-controller: api.user
      operationId: validate
      parameters:
        - name: key
          in: query
          type: string
      responses:
        200:
          description: Token info object
          schema:
            $ref: '#/definitions/User'
  /users/register:
    post:
      tags: [Users]
      summary: Registration end point for a user account
      x-swagger-router-controller: api.user
      operationId: register_user
      parameters:
        - name: user
          in: body
          schema:
            $ref: '#/definitions/User'
      responses:
        200:
          description: Created user
  /users/login:
    post:
      tags: [Users]
      x-swagger-router-controller: api.user
      operationId: login
      summary: Allow a user to login
      parameters:
        - name: user
          in: body
          required: true
          schema:
            $ref: '#/definitions/User'
      responses:
        200:
          description: Login successful
        401:
          description: Incorrect login details
        404:
          description: User not found
  /users/{id}:
    get:
      security:
         - apiKeyHeader: []
      tags: [Users]
      x-swagger-router-controller: api.user
      operationId: get_user
      summary: Get all users (or those matching an ID)
      parameters:
        - $ref: '#/parameters/id' 
      responses:
        200:
          description: Return users
          schema:
            $ref: '#/definitions/User'
        404:
          description: User not found
  /projects:
    get:
      tags: [Projects]
      x-swagger-router-controller: api.project
      operationId: get_projects
      summary: Get all projects
      parameters:
        - name: search_term
          in: query
          type: string
        - name: limit
          in: query
          type: integer
          minimum: 0
          default: 20
      responses:
        200:
          description: Return projects
          schema:
            type: array
            items:
              $ref: '#/definitions/Project'
    post:
      security:
        - apiKeyHeader: []
      tags: [Projects]
      x-swagger-router-controller: api.project
      operationId: create_project
      summary: Post a project
      parameters:
        - name: project
          in: body
          schema:
            $ref: '#/definitions/Project'
      responses:
        201:
          description: New project created
  /projects/{id}:
    get:
      security:
        - apiKeyHeader: []
      tags: [Projects]
      x-swagger-router-controller: api.project
      operationId: get_project
      summary: Get a single project
      parameters:
        - $ref: '#/parameters/id'
      responses:
        200:
          description: Return project
        404:
          description: Project does not exist
    put:
      security:
        - apiKeyHeader: []
      tags: [Projects]
      x-swagger-router-controller: api.project
      operationId: put_project
      summary: Modify/Create a project
      parameters:
        - $ref: '#/parameters/id'
        - name: project
          in: body
          schema:
            $ref: '#/definitions/Project'
      responses:
        200:
          description: Project modified
        201:
          description: New project created
    delete:
      security:
        - apiKeyHeader: []
      tags: [Projects]
      x-swagger-router-controller: api.project
      operationId: delete_project
      summary: Remove a project
      parameters:
        - $ref: '#/parameters/id'
      responses:
        204:
          description: Project was deleted
        404:
          description: Project does not exist
  /projects/{id}/stats:
    get:
      security:
        - apiKeyHeader: []
      tags: [Projects]
      parameters:
        - $ref: '#/parameters/id'
      x-swagger-router-controller: api.project
      operationId: get_stats
      responses:
        200: 
          description: Project stats
        404:
          description: Project does not exist
  /projects/{id}/tasks:
    get:
      security:
        - apiKeyHeader: []
      tags: [Projects]
      parameters:
        - $ref: '#/parameters/id'
        - name: limit
          in: query
          type: integer
          minimum: 0
          default: 20
      x-swagger-router-controller: api.task
      operationId: project_tasks
      responses:
        200:
          description: Project tasks
        404:
          description: Project does not exist
  /tasks:
    get:
      security:
        - apiKeyHeader: []
      tags: [Tasks]
      x-swagger-router-controller: api.task
      operationId: get_tasks
      summary: Get a list of tasks
      parameters:
        - name: search_term
          in: query
          type: string
        - name: limit
          in: query
          type: integer
          minimum: 0
          default: 20
      responses:
        200:
          description: List of tasks
          schema:
            type: array
            items: 
              $ref: '#/definitions/Task'
    post:
      security:
        - apiKeyHeader: []
      tags: [Tasks]
      x-swagger-router-controller: api.task
      operationId: create_tasks
      summary: Post an array of tasks
      parameters:
        - name: tasks
          in: body
          schema:
            type: array
            items:
              $ref: '#/definitions/Task'
      responses:
        200:
          description: Task created
          schema:
            $ref: '#/definitions/Task'
    delete:
      security:
        - apiKeyHeader: []
      tags: [Tasks]
      x-swagger-router-controller: api.task
      operationId: delete_tasks
      summary: Delete an array of tasks
      parameters:
        - name: tasks
          in: body
          schema:
            type: array
            items:
              type: string
      responses:
        204:
          description: Tasks were deleted
  /tasks/{id}:
    get:
      security:
        - apiKeyHeader: []
      tags: [Tasks]
      x-swagger-router-controller: api.task
      operationId: get_task
      summary: Get a single task
      parameters:
        - $ref: '#/parameters/id'
      responses:
        200:
          description: Return task
          schema:
            $ref: '#/definitions/Task'
        404:
          description: Task does not exist
    put:
      security:
        - apiKeyHeader: []
      tags: [Tasks]
      x-swagger-router-controller: api.task
      operationId: put_task
      summary: Modify/Create a task
      parameters:
        - $ref: '#/parameters/id'
        - name: task
          in: body
          schema:
            $ref: '#/definitions/Task'
      responses:
        200:
          description: Task modified
        201:
          description: New task created
    delete:
      security:
        - apiKeyHeader: []
      tags: [Tasks]
      x-swagger-router-controller: api.task
      operationId: delete_task
      summary: Delete a single tasks
      parameters:
        - $ref: '#/parameters/id'
      responses:
        204:
          description: Task was deleted
  /submissions:
    get:
      security:
        - apiKeyHeader: []
      tags: [Submissions]
      x-swagger-router-controller: api.submission
      operationId: get_submissions
      summary: Get a single submission
      parameters:
        - name: search_term
          in: query
          type: string
        - name: limit
          in: query
          type: integer
          minimum: 0
          default: 20
      responses:
        200:
          description: List of tasks
          schema:
            type: array
            items: 
              $ref: '#/definitions/Submission'
    post:
      security:
        - apiKeyHeader: []
      tags: [Submissions]
      x-swagger-router-controller: api.submission
      operationId: create_submission
      summary: Post a submission
      parameters:
        - name: submission
          in: body
          schema:
            $ref: '#/definitions/Submission'
      responses:
        200:
          description: Submission created
          schema:
            $ref: '#/definitions/Submission'
    put:
      security:
        - apiKeyHeader: []
      tags: [Submissions]
      x-swagger-router-controller: api.submission
      operationId: put_submission
      summary: Modify/Create a submission
      parameters:
        - $ref: '#/parameters/id'
        - name: submission
          in: body
          schema:
            $ref: '#/definitions/Submission'
      responses:
        200:
          description: Submission modified
        201:
          description: New submission created
    delete:
      security:
        - apiKeyHeader: []
      tags: [Submissions]
      x-swagger-router-controller: api.submission
      operationId: delete_submission
      summary: Remove a submission
      parameters:
        - $ref: '#/parameters/id'
      responses:
        204:
          description: Submission was deleted
        404:
          description: Submission does not exist
  /submission/{id}:
    get:
      security:
        - apiKeyHeader: []
      tags: [Submissions]
      x-swagger-router-controller: api.submission
      operationId: get_submission
      summary: Get a single submission
      parameters:
        - $ref: '#/parameters/id'
      responses:
        200:
          description: Return submission
          schema:
            $ref: '#/definitions/Submission'
        404:
          description: Submission does not exist
  /media:
    post:
      security:
        - apiKeyHeader: []
      tags: [Media]
      description: "Add a new media attachment"
      x-swagger-router-controller: api.media
      operationId: upload
      consumes:
      - multipart/form-data
      parameters:
      - name: attachment
        in: formData
        description: The file to be uploaded
        type: file
        required: true
      - name: id
        in: formData
        type: string
        required: false
      responses:
        200:
          description: Media attached
    get:
      security:
        - apiKeyHeader: []
      tags: [Media]
      description: "Get a list of media"
      x-swagger-router-controller: api.media
      operationId: get_media
      parameters:
        - name: search_term
          in: query
          type: string
        - name: limit
          in: query
          type: integer
          minimum: 0
          default: 20
      responses:
        200:
          description: List of media
          schema:
            type: array
            items: 
              $ref: '#/definitions/Media'
  /media/{id}:
    get:
      security:
        - apiKeyHeader: []
      tags: [Media]
      x-swagger-router-controller: api.media
      operationId: get_medium
      summary: Get a single file
      parameters:
        - $ref: '#/parameters/id'
      responses:
        200:
          description: Return Media
          schema:
            type: file
        404:
          description: Media does not exist
    put:
      security:
        - apiKeyHeader: []
      tags: [Media]
      x-swagger-router-controller: api.media
      operationId: put_medium
      summary: Put a single file
      parameters:
        - $ref: '#/parameters/id'
        - name: media
          in: body
          schema:
            $ref: '#/definitions/Media'
      responses:
        201:
          description: Return Media
          schema:
            $ref: '#/definitions/Media' 
        404:
          description: Media does not exist
  /media/source/{id}:
    get:
      security:
        - apiKeyHeader: []
      tags: [Media]
      x-swagger-router-controller: api.media
      operationId: get_for_source
      summary: Query media for a specific task or project
      parameters:
        - $ref: '#/parameters/id'
      responses:
        200:
          description: Return Media
          schema:
            type: array
            items: 
              $ref: '#/definitions/Media'
        404:
          description: Media does not exist
    delete:
      security:
         - apiKeyHeader: []
      tags: [Media]  
      x-swagger-router-controller: api.media
      operationId: delete_medium
      summary: Delete a single Media file
      parameters:
        - $ref: '#/parameters/id'
      responses:
        200:
          description: Media deleted
        404:
          description: Media does not exist
parameters:
  id:
    name: id
    description: The unique identifer for an Object (i.e. User, Task, Project, Submission etc)
    in: path
    type: string
    required: true
    pattern: "^[a-zA-Z0-9-]+$"
definitions:
  User:
    type: object
    required:
      - email
      - pwd
    properties:
      id:
        type: string
        maxLength: 20
        readOnly: true
      username:
        type: string
      email:
        type: string
        format: email
      pwd:
        type: string
      api_key:
        type: string
      created_at:
        type: string
        format: date-time
        description: Creation time
        example: "2015-07-07T15:49:51.230+02:00"
        readOnly: true
      updated_at:
        type: string
        format: date-time
        description: Creation time
        example: "2015-07-07T15:49:51.230+02:00"
        readOnly: true
  Otoken:
    type: object
    required:
      - user_id
      - project_id
    properties:
      id:
        type: string
        readOnly: true
      user_id:
        type: string
      project_id:
        type: string
      created_at:
        type: string
        format: date-time
        description: Creation time
        example: "2015-07-07T15:49:51.230+02:00"
        readOnly: true
      updated_at:
        type: string
        format: date-time
        description: Creation time
        example: "2015-07-07T15:49:51.230+02:00"
        readOnly: true
  Project:
    type: object
    required:
      - name
      - description
      - platform
    properties:
      id:
        type: string
        readOnly: true
        description: Unique project ID
      name:
        type: string
      description:
        type: string
      platform:
        type: string
        enum:
          - Desktop
          - Mobile
          - Both
      owned_by:
        type: string
      created_at:
        type: string
        format: date-time
        description: Creation time
        example: "2015-07-07T15:49:51.230+02:00"
        readOnly: true
      updated_at:
        type: string
        format: date-time
        description: Creation time
        example: "2015-07-07T15:49:51.230+02:00"
        readOnly: true
  Media:
    type: object
    required:
      - id
    properties:
      id:
        type: string
        description: Uniqe media ID
      source_id:
        type: string
        description: linking to a task or a submission
      path:
        type: string
        description: location on filesystem
      name: 
        type: string
      filetype:
        type: string
  Task:
    type: object
    required:
      - project_id
      - sequence
      - title
      - content
      - required
    properties:
      id:
        type: string
        readOnly: true
        description: Unique task ID
      project_id:
        type: string
      sequence:
        type: integer
      content:
        type: object
      title:
        type: string
      required:
        type: boolean
      created_at:
        type: string
        format: date-time
        description: Creation time
        example: "2015-07-07T15:49:51.230+02:00"
        readOnly: true
      updated_at:
        type: string
        format: date-time
        description: Creation time
        example: "2015-07-07T15:49:51.230+02:00"
        readOnly: true
  Submission:
    type: object
    required:
      - task_id
      - user_id
    properties:
      id:
        type: string
        readOnly: true
      task_id:
        type: string
      user_id:
        type: string
      content:
        type: object
