swagger: '2.0'
info:
  title: CCCS
  version: "0.1"
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  apiKeyHeader:
    type: apiKey
    in: header
    name: X-API-KEY
  oauth2:
    type: oauth2
    flow: implicit
    authorizationUrl: http://wenker.citizenscience.ch:8080/oauth/authorize
    # the token info URL is hardcoded for our mock_tokeninfo.py script
    # you can also pass it as an environment variable TOKENINFO_URL
    x-tokenInfoUrl: http://wenker.citizenscience.ch:8080/api/v1/users/validate
    scopes:
      apiKey: Unique identifier of the user accessing the service.
host: wenker.citizenscience.ch:8080
basePath: /api/v1
schemes:
  - http
  - https
paths:
  $ref: 'paths/index/yaml'
  