openapi: 3.0.1
info:
  title: An include file to define requestBodies
  version: 1.0.0
paths: {}
components:
  requestBodies:
    User:
      x-nullable: true
      content:
        application/json:
          schema:
            $ref: './schemas.yaml#/components/schemas/User'
    UserUpdate:
      content:
        application/json:
          schema:
            $ref: './schemas.yaml#/components/schemas/UserUpdate'
    Comment:
      content:
        application/json:
          schema:
            $ref: './schemas.yaml#/components/schemas/Comment'
    Medium:
      content:
        application/json:
          schema:
            $ref: './schemas.yaml#/components/schemas/Media'
    Media:
      content:
        application/json:
          type: array
          items:
            $ref: './schemas.yaml#/components/schemas/Media'
    Activity:
      content:
        application/json:
          schema:
            $ref: './schemas.yaml#/components/schemas/Activity'
    Submission:
      content:
        application/json:
          schema:
            $ref: './schemas.yaml#/components/schemas/Submission'
    Project:
      content:
        application/json:
          schema:
            $ref: './schemas.yaml#/components/schemas/Project'
    Task:
      content:
        application/json:
          schema:
            $ref: './schemas.yaml#/components/schemas/Task'
    Tasks:
      content:
        application/json:
          schema:
                  type: array
                  items:
                    $ref: './schemas.yaml#/components/schemas/Task'
        
