openapi: 3.0.1
info:
  title: An include file to define requestBodies
  version: 1.0.0
paths: {}
components:
  requestBodies:
    User:
      content:
        application/json:
          schema:
            $ref: './schemas.yaml#/components/schemas/User'
    Comment:
      content:
        application/json:
          schema:
            $ref: './schemas.yaml#/components/schemas/Comment'
    Media:
      content:
        application/json:
          schema:
            $ref: './schemas.yaml#/components/schemas/Media'
    Activity:
      content:
        application/json:
          schema:
            $ref: './schemas.yaml#/components/schemas/Activity'
    Submission:
      content:
        application/json:
          schema:
            $ref: './schemas.yaml#/components/schemas/Submission'
    Project:
      content:
        application/json:
          schema:
            $ref: './schemas.yaml#/components/schemas/Project'
    Task:
      content:
        application/json:
          type: array
          items:
            $ref: './schemas.yaml#/components/schemas/Task'