components:
  securitySchemes:
    anonUser:
      in: header
      name: X-ANON
      type: apiKey
      x-apikeyInfoFunc: decorators.access_checks.ensure_anon_key
    apiKeyHeader:
      in: header
      name: X-API-KEY
      type: apiKey
      x-apikeyInfoFunc: decorators.access_checks.ensure_key
    oauth2:
      flows:
        implicit:
          authorizationUrl: http://localhost:8081/oauth/authorize
          scopes:
            apiKey: 'Unique identifier of the user accessing the service.'
      type: oauth2
      x-tokenInfoUrl: http://localhost:8081/api/v1/users/validate
info:
  title: C3S API]
  description: An API for creating, running and analysing citizen science projects
  version: 3.1.2
openapi: 3.0.0
paths:
  # Project Group Endpoints
  /project-groups:
    $ref: 'endpoints/project_group/all.yml#/paths/~1project_groups'
  /project-groups/{gid}:
    $ref: 'endpoints/project_group/id.yml#/paths/~1project_groups~1{gid}'
  /project-groups/{gid}/projects:
    $ref: 'endpoints/project_group/projects.yml#/paths/~1project_groups~1{gid}~1projects'
  /project-groups/{gid}/invite:
    $ref: 'endpoints/project_group/id.yml#/paths/~1invite'
  /project-groups/{gid}/members:
    $ref: 'endpoints/project_group/id.yml#/paths/~1members'
  # Project Endpoints
  /projects:
    $ref: 'endpoints/project/all.yml#/paths/projects'
  /projects/{pid}:
    $ref: 'endpoints/project/id.yml#/paths/project_id'
  /projects/{pid}/invite:
    $ref: 'endpoints/project/members.yml#/paths/invite'
  /projects/{pid}/members:
    $ref: 'endpoints/project/members.yml#/paths/get'
  /projects/{pid}/submissions:
    $ref: 'endpoints/project/submissions.yml#/paths/all'
  /projects/{pid}/publish:
    $ref: 'endpoints/project/publish.yml#/paths/publish'
  /projects/{pid}/stats:
    $ref: 'endpoints/project/stats.yml#/paths/stats'
  /projects/{pid}/import/tasks/csv:
    $ref: 'endpoints/project/import.yml#/paths/import_tasks_csv'
  /projects/{pid}/reimport/tasks/csv:
    $ref: 'endpoints/project/import.yml#/paths/reimport_tasks_csv'
  /projects/{pid}/submissions/{uid}:
    $ref: 'endpoints/project/submissions.yml#/paths/user'
  /projects/{pid}/tasks:
    $ref: 'endpoints/project/tasks.yml#/paths/all'
  /projects/{pid}/task:
    $ref: 'endpoints/project/tasks.yml#/paths/one'
  /projects/{pid}/media:
    $ref: 'endpoints/project/media.yml#/paths/all'
  # Comment Endpoints
  /comments:
    $ref: 'endpoints/comment/all.yml#/paths/all'
  /comments/{cid}:
    $ref: 'endpoints/comment/id.yml#/paths/id'
  # Media Endpoints
  /media:
    $ref: 'endpoints/media/all.yml#/paths/all'
  /media/source/{sid}:
    $ref: 'endpoints/media/all.yml#/paths/source'
  /media/upload:
    $ref: 'endpoints/media/upload.yml#/paths/upload'
  /media/{mid}:
    $ref: 'endpoints/media/id.yml#/paths/id'
  # Submission Endpoints
  /submissions:
    $ref: 'endpoints/submission/all.yml#/paths/all'
  /submission/{sid}:
    $ref: 'endpoints/submission/id.yml#/paths/id'
  # Task Endpoints
  /task:
    $ref: 'endpoints/task/one.yml#/paths/one'
  /tasks:
    $ref: 'endpoints/task/all.yml#/paths/all'
  /tasks/{tid}:
    $ref: 'endpoints/task/id.yml#/paths/id'
  /tasks/{tid}/media:
    $ref: 'endpoints/task/media.yml#/paths/media'
  /tasks/{tid}/submissions:
    $ref: 'endpoints/task/submissions.yml#/paths/submissions'
  /tasks/{tid}/stats:
    $ref: 'endpoints/task/stats.yml#/paths/stats'
  # Users Endpoints
  /users/authorize:
    $ref: 'endpoints/user/authorize.yml#/paths/auth'
  /users/check:
    $ref: 'endpoints/user/check.yml#/paths/check'
  /users/login:
    $ref: 'endpoints/user/login.yml#/paths/login'
  /users/me:
    $ref: 'endpoints/user/me.yml#/paths/me'
  /users/register:
    $ref: 'endpoints/user/register.yml#/paths/register'
  /users/reset:
    $ref: 'endpoints/user/reset.yml#/paths/reset'
  /users/validate:
    $ref: 'endpoints/user/validate.yml#/paths/validate'
  /users/me/submissions:
    $ref: 'endpoints/user/submissions.yml#/paths/submissions'
  /users/me/projects:
    $ref: 'endpoints/user/projects.yml#/paths/projects'
servers:
  - description: Testing/Dev Server
    url: http://localhost:9000/api/v3
  - description: 'Staging Server'
    url: https://staging.citizenscience.ch/api/v3
  - description: 'Production API Server'
    url: https://api.citizenscience.ch/v3
