DB_URI = 'postgresql://pybossa:tester@localhost/cs'
PORT = 8080
DEBUG = True
SWAGGER_DIR='swagger/'
SWAGGER_FILE='swagger.json'
SECRET_KEY='SUPES_SECRET987'
TEST_USER = 'test@test.com'
TEST_PWD = 'test'
TESTING = True