apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: cccs-connexion
  name: cccs-connexion
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: cccs-connexion
    spec:
      containers:
      - args:
        - uwsgi
        - --http
        - :8080
        - --wsgi-file
        - uwsgi.py
        - --master
        - --processes
        - "4"
        - --threads
        - "2"
        - --stats
        - :9191
        image: cccs-connexion
        name: cccs-connexion
        ports:
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - mountPath: /code/static/upload
          name: cccs-connexion-claim0
      restartPolicy: Always
      volumes:
      - name: cccs-connexion-claim0
        persistentVolumeClaim:
          claimName: cccs-connexion-claim0
status: {}
