apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o helm
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: graphql
  name: graphql
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: graphql
    spec:
      containers:
      - args:
        - postgraphile
        - --connection
        - postgresql://stager:XiTNvo7qzqiivt@130.60.24.245/cs?sslmode=disable
        - --host
        - 0.0.0.0
        - --port
        - "5000"
        - --schema
        - public
        - -a
        - -j
        image: graphile/postgraphile
        name: graphql
        ports:
        - containerPort: 5000
        resources: {}
      restartPolicy: Always
status: {}
