apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: swagger-ui
  name: swagger-ui
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: swagger-ui
    spec:
      containers:
      - env:
        - name: URL
          value: http://localhost:8080/api/v2/swagger.json
        image: swaggerapi/swagger-ui:latest
        name: swagger-ui
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
